title: Abidi Syed Parvaiz
logo: /assets/img/images.png
description: Abidi Parvaiz, Working in Microsoft Technologies from last 15+ years of Experience in SDLC, SQL handling different projects of Educational and medical domain.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
